spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dkm_game?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: dkm123456..
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
<<<<<<< HEAD
    host: 124.232.163.75
=======
    host: localhost
>>>>>>> 03f5895658cde03afba7a72c16b02772b2078b9e
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
  redis:
<<<<<<< HEAD
    host: 124.232.163.75
=======
    host: localhost
>>>>>>> 03f5895658cde03afba7a72c16b02772b2078b9e
    timeout: 2000
    jedis:
      pool:
        max-wait: 1000
        max-active: 20
        min-idle: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
<<<<<<< HEAD
      defaultZone: http://124.232.163.75:10000/eureka
=======
      defaultZone: http://localhost:10000/eureka
>>>>>>> 03f5895658cde03afba7a72c16b02772b2078b9e

feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 10000

hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 4000
<<<<<<< HEAD
=======
family:
  url: http://localhost:8002
>>>>>>> 03f5895658cde03afba7a72c16b02772b2078b9e

