server:
  port: 8002
  max-http-header-size: 102400
mybatis-plus:
  mapper-locations: classpath:com/dkm/*/dao/mapper/*.xml
spring:
  profiles:
    active: test
  application:
    name: service-family
  jmx:
    enabled: false

app:
  workerId: 9
  dataCenterId: 1
