server:
  port: 7001
  max-http-header-size: 102400
mybatis-plus:
  mapper-locations: classpath:com/dkm/*/dao/mapper/*.xml
spring:
  profiles:
    active: local
  application:
    name: family
  jmx:
    enabled: false

app:
  workerId: 9
  dataCenterId: 1
urls:
  family: http://124.232.163.75:8000/game/family
