server:
  port: 8000
spring:
  application:
#    name: game-eureka
    name: game-gateway
  profiles:
    active: local
eureka:
  client:
    service-url:
      defaultZone: http://192.168.10.133:10000/eureka

zuul:
  routes:
    api-user:
      path: /game-user/**
      serviceId: service-user
      strip-prefix: true
    api-base:
      path: /game-base/**
      serviceId: service-base
      strip-prefix: true
    api-family:
      path: /*/*/game-family/**
      serviceId: service-family
      strip-prefix: false
    api-resource:
      path: /*/*/game-resource/**
      serviceId: service-resource
      strip-prefix: false
    api-shop:
      path: /*/*/game-shop/**
      serviceId: service-shop
      strip-prefix: false
    api-chat:
      path: /*/*/game-chat/**
      serviceId: service-chat
      strip-prefix: false
