server:
  port: 8000
spring:
  application:
    name: game-gateway
  profiles:
    active: local
  jmx:
    enabled: false

zuul:
  routes:
    api-user:
      path: /*/*/user/**
      serviceId: user
      strip-prefix: false
    api-base:
      path: /*/*/base/**
      serviceId: base
    api-family:
      path: /*/*/family/**
      serviceId: family
      strip-prefix: false
    api-resource:
      path: /*/*/resource/**
      serviceId: resource
      strip-prefix: false
    api-shop:
      path: /*/*/shop/**
      serviceId: shop
      strip-prefix: false
    api-chat:
      path: /*/*/chat/**
      serviceId: chat
      strip-prefix: false
    api-back:
      path: /*/*/back/**
      serviceId: back
      strip-prefix: false
    file-url:
      path: /file/**
      url: http://${service.ip}:7000/game-file/
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 20000

service:
  ip: 192.168.10.133

ribbon:
  ReadTimeout: 10000
  SocketTimeout: 20000
