app:
  workerId: 1
  dataCenterId: 2

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${service.ip}:10000/eureka

spring:
  redis:
    host: ${service.ip}

service:
  ip: 192.168.10.254
