server:
  port: 8000
spring:
  application:
<<<<<<< HEAD
#    name: game-eureka
=======
>>>>>>> c245512e3daf3c070b3d1c26bec114a9fd676647
    name: game-gateway
  profiles:
    active: local

zuul:
  routes:
    api-user:
      path: /game-user/**
      serviceId: service-user
      strip-prefix: true
    api-base:
      path: /game-base/**
      serviceId: service-base
      strip-prefix: true
    api-family:
      path: /*/*/game-family/**
      serviceId: service-family
      strip-prefix: false
    api-resource:
      path: /*/*/game-resource/**
      serviceId: service-resource
      strip-prefix: false
    api-shop:
      path: /*/*/game-shop/**
      serviceId: service-shop
      strip-prefix: false
    api-chat:
      path: /*/*/game-chat/**
      serviceId: service-chat
      strip-prefix: false
