server:
  port: 8000
spring:
  application:
    name: game-gateway
  profiles:
    active: local
  jmx:
    enabled: false

zuul:
  routes:
    api-user:
      path: /*/*/user/**
      serviceId: user
      strip-prefix: false
    api-base:
      path: /*/*/base/**
      serviceId: base
      strip-prefix: false
    api-family:
      path: /*/*/family/**
      serviceId: family
      strip-prefix: false
    api-resource:
      path: /*/*/resource/**
      serviceId: resource
      strip-prefix: false
    api-shop:
      path: /*/*/shop/**
      serviceId: shop
      strip-prefix: false
    api-chat:
      path: /*/*/chat/**
      serviceId: chat
      strip-prefix: false
    api-file:
      path: /*/*/file/**
      serviceId: file
    api-back:
      path: /*/*/back/**
      serviceId: back
      strip-prefix: false
