app:
  workerId: 1
  dataCenterId: 2

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://124.232.163.75:10000/eureka

spring:
  redis:
    host: 124.232.163.75