server:
  port: 8000
spring:
  application:
    name: game-gateway
  profiles:
    active: local
  jmx:
    enabled: false


zuul:
  routes:
    api-user:
      path: /*/*/game-user/**
      serviceId: user
      strip-prefix: false
    api-base:
      path: /*/*/game-base/**
      serviceId: base
      strip-prefix: false
    api-family:
      path: /*/*/game-family/**
      serviceId: family
      strip-prefix: false
    api-resource:
      path: /*/*/game-resource/**
      serviceId: resource
      strip-prefix: false
    api-shop:
      path: /*/*/game-shop/**
      serviceId: shop
      strip-prefix: false
    api-chat:
      path: /*/*/game-chat/**
      serviceId: chat
      strip-prefix: false
    api-file:
      path: /*/*/game-file/**
      serviceId: file
      strip-prefix: false
