spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://124.232.163.75:10000/eureka

file:
  url: http://124.232.163.75:8000/game/family/img