server:
  port: 7007
  max-http-header-size: 102400
spring:
  profiles:
    active: local
  application:
    name: file
  jmx:
    enabled: false
  datasource:
    hikari:
      max-lifetime: 60000
      idle-timeout: 60000
      connection-timeout: 50000
      maximum-pool-size: 60
      minimum-idle: 10
app:
  workerId: 9
  dataCenterId: 1
