spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: 192.168.10.133
    timeout: 2000
    jedis:
      pool:
        min-idle: 1
        max-active: 20
        max-wait: 1000


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.10.133:10000/eureka

file:
  url: http://192.168.10.133:7000/game-file/img
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 10000
hystrix:
    metrics:
      enabled: true
      polling-interval-ms: 4000

ribbon:
  eureka:
    enabled: true


