server:
  port: 8004
  max-http-header-size: 102400
mybatis-plus:
  mapper-locations: classpath:com/dkm/*/dao/mapper/*.xml
spring:
  profiles:
    active: dev
  application:
    name: resource
  jmx:
    enabled: false


app:
  workerId: 9
  dataCenterId: 1
