spring:
  datasource:
    url: jdbc:mysql://192.168.10.133:3306/dkm_game?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: kgdatj1110
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.10.133
    timeout: 2000
    jedis:
      pool:
        max-wait: 1000
        max-active: 20
        min-idle: 1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB



eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.10.133:10000/eureka

file:
  url: http://192.168.10.133:8000/game/resource/img
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 10000
hystrix:
    metrics:
      enabled: true
      polling-interval-ms: 4000

ribbon:
  eureka:
    enabled: true


