server:
  port: 8004
  max-http-header-size: 102400
mybatis-plus:
  mapper-locations: classpath:com/dkm/*/dao/mapper/*.xml
spring:
  profiles:
    active: local
  application:
    name: resource
  jmx:
    enabled: false
  datasource:
    hikari:
      max-lifetime: 60000
      idle-timeout: 60000
      connection-timeout: 50000
      maximum-pool-size: 60
      minimum-idle: 10

app:
  workerId: 9
  dataCenterId: 1
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000