
spring:
  rabbitmq:
<<<<<<< HEAD
    host: 127.0.0.1
=======
    host: localhost
>>>>>>> 14fcf3cab314a04f95f8167b8a168f0a435fb63e
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
  redis:
<<<<<<< HEAD
    host: 127.0.0.1
=======
    host: localhost
>>>>>>> 14fcf3cab314a04f95f8167b8a168f0a435fb63e
    timeout: 2000
    jedis:
      pool:
        min-idle: 1
        max-active: 20
        max-wait: 1000


app:
  workerId: 1
  dataCenterId: 2

