spring:
  datasource:
    url: jdbc:mysql://120.25.196.49:3306/dkm_game?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 120.25.196.49
    timeout: 2000
    jedis:
      pool:
        max-wait: 1000
        max-active: 20
        min-idle: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://120.25.196.49:10000/eureka
