server:
  port: 8002
  max-http-header-size: 102400
mybatis-plus:
  mapper-locations: classpath:com/dkm/*/dao/mapper/*.xml
spring:
  profiles:
    active: dev
  application:
    name: base
  jmx:
    enabled: false
app:
  workerId: 9
  dataCenterId: 1
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000