spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dkm_game?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: dkm123456..
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    timeout: 2000
    jedis:
      pool:
        max-wait: 1000
        max-active: 20
        min-idle: 1
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true

<<<<<<< HEAD
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dkm_game?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: dkm123456..
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    timeout: 2000
    jedis:
      pool:
        max-wait: 1000
        max-active: 20
        min-idle: 1
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
    virtual-host: /

=======
>>>>>>> 14fcf3cab314a04f95f8167b8a168f0a435fb63e
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 10000

<<<<<<< HEAD
hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 4000
=======

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #断路器超时时间，默认1000ms
>>>>>>> 14fcf3cab314a04f95f8167b8a168f0a435fb63e
