spring:
  datasource:
<<<<<<< HEAD
<<<<<<< HEAD
    url: jdbc:mysql://127.0.0.1:3306/dkm_game?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
=======
    url: jdbc:mysql://localhost:3306/dkm_game?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
>>>>>>> 14fcf3cab314a04f95f8167b8a168f0a435fb63e
=======
    url: jdbc:mysql://127.0.0.1:3306/dkm_game?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
>>>>>>> c1f355446e715fb1ef2e753272a42a5e5d1e239c
    username: root
    password: dkm123456..
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
<<<<<<< HEAD
<<<<<<< HEAD
    host: 127.0.0.1
=======
    host: localhost
>>>>>>> 14fcf3cab314a04f95f8167b8a168f0a435fb63e
=======
    host: 127.0.0.1
>>>>>>> c1f355446e715fb1ef2e753272a42a5e5d1e239c
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
  redis:
<<<<<<< HEAD
<<<<<<< HEAD
    host: 127.0.0.1
=======
    host: localhost
>>>>>>> 14fcf3cab314a04f95f8167b8a168f0a435fb63e
=======
    host: 127.0.0.1
>>>>>>> c1f355446e715fb1ef2e753272a42a5e5d1e239c
    timeout: 2000
    jedis:
      pool:
        max-wait: 1000
        max-active: 20
        min-idle: 1
<<<<<<< HEAD
=======

>>>>>>> 14fcf3cab314a04f95f8167b8a168f0a435fb63e
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
<<<<<<< HEAD
<<<<<<< HEAD
      defaultZone: http://127.0.0.1:10000/eureka
=======
      defaultZone: http://localhost:10000/eureka
>>>>>>> 14fcf3cab314a04f95f8167b8a168f0a435fb63e
=======
      defaultZone: http://127.0.0.1:10000/eureka
>>>>>>> c1f355446e715fb1ef2e753272a42a5e5d1e239c
file:
  # 前端地址   跳转搜索群聊的页面
  qrCodeUrl: http://www.baidu.com
