spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://127.0.0.1:3306/dkm_game?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
=======
    url: jdbc:mysql://localhost:3306/dkm_game?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
>>>>>>> 14fcf3cab314a04f95f8167b8a168f0a435fb63e
    username: root
    password: dkm123456..
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
<<<<<<< HEAD
    host: 127.0.0.1
=======
    host: localhost
>>>>>>> 14fcf3cab314a04f95f8167b8a168f0a435fb63e
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
  redis:
<<<<<<< HEAD
    host: 127.0.0.1
=======
    host: localhost
>>>>>>> 14fcf3cab314a04f95f8167b8a168f0a435fb63e
    timeout: 2000
    jedis:
      pool:
        max-wait: 1000
        max-active: 20
        min-idle: 1
<<<<<<< HEAD
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
=======
>>>>>>> 14fcf3cab314a04f95f8167b8a168f0a435fb63e
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 10000

hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 4000
