server:
  port: 8003
  max-http-header-size: 102400
mybatis-plus:
  mapper-locations: classpath:com/dkm/*/dao/mapper/*.xml
spring:
  profiles:
    active: local
  application:
    name: user
  jmx:
    enabled: false
  datasource:
    hikari:
      max-lifetime: 60000
      idle-timeout: 60000
      connection-timeout: 50000
      maximum-pool-size: 60
      minimum-idle: 10
app:
  workerId: 9
  dataCenterId: 1

file:
  #  前端地址   二维码地址  跳转到搜索好友页面
  qrCodeUrl: http://www.baidu.com

#微信密钥
weChat:
  access:
    token:
      url: https://api.weixin.qq.com/sns/oauth2/access_token
      confirmation:
        url: https://api.weixin.qq.com/sns/auth
  app:
    id: wx69abe63fb3af0007
  secret: 0d53a67db5ed991d697999001657e621
  user:
    info:
      url: https://api.weixin.qq.com/sns/userinfo