logging:
  level:
    org.springframework: WARN
    org.spring.springboot.dao: DEBUG
    com.dkm.shop.dao: DEBUG
server:
  port: 8004
  max-http-header-size: 102400
mybatis-plus:
  mapper-locations: classpath:com/dkm/*/dao/mapper/*.xml
spring:
  profiles:
    active: local
  application:
    name: shop
  jmx:
    enabled: false

app:
  workerId: 9
  dataCenterId: 1
